apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  application-name: simple-quarkus
  org: wanja.org

resources:
- config-map.yaml
- deployment.yaml
- service.yaml
- route.yaml

